// Popular Binance Spot USDT pairs (stablecoins excluded). Run `bun run check:symbols`
// to verify every pair is still TRADING on spot before adding or after delistings.
export const SYMBOLS: readonly string[] = [
  'BTCUSDT', 'ETHUSDT', 'SOLUSDT', 'XRPUSDT', 'BNBUSDT', 'DOGEUSDT', 'ZECUSDT', 'BCHUSDT', 'SUIUSDT', 'PAXGUSDT',
  'ENAUSDT', 'ADAUSDT', 'LINKUSDT', 'UNIUSDT', 'AVAXUSDT', 'WLFIUSDT', 'TRXUSDT', 'LTCUSDT', 'FLOWUSDT', 'NEARUSDT',
  'PUMPUSDT', 'FILUSDT', 'TRUMPUSDT', 'AAVEUSDT', 'WIFUSDT', 'DOTUSDT', 'TAOUSDT', 'XPLUSDT', 'APTUSDT',
  'WLDUSDT', 'ARBUSDT', 'XLMUSDT', 'PENGUUSDT', 'FETUSDT', 'ICPUSDT', 'HBARUSDT', 'ETCUSDT', 'VIRTUALUSDT',
  'CRVUSDT', 'ONDOUSDT', 'TIAUSDT', 'SEIUSDT', 'GIGGLEUSDT', 'ATOMUSDT', 'KITEUSDT', 'JASMYUSDT', 'BARDUSDT', 'LDOUSDT',
  'INJUSDT', 'DASHUSDT', 'STRKUSDT', 'BROCCOLI714USDT', 'POLUSDT', 'ETHFIUSDT', 'RENDERUSDT', 'AVNTUSDT', 'PARTIUSDT', 'JUPUSDT',
  'PENDLEUSDT', 'ACTUSDT', 'CHZUSDT', 'CAKEUSDT', 'ALTUSDT', 'EIGENUSDT', 'HUMAUSDT', 'GALAUSDT', 'KAITOUSDT', 'PNUTUSDT',
  'VETUSDT', 'ALGOUSDT', 'ZROUSDT', 'SOLVUSDT', 'GRTUSDT', 'ENJUSDT', 'SNXUSDT', 'CFXUSDT', 'BATUSDT',
  'KAVAUSDT', 'KSMUSDT', 'ONEUSDT', 'QTUMUSDT', 'RUNEUSDT', 'IOSTUSDT', 'SUSHIUSDT', 'ZILUSDT', 'ZRXUSDT', 'ARUSDT',
  'CELOUSDT', 'COMPUSDT', 'DYDXUSDT', 'EGLDUSDT', 'ENSUSDT', 'IMXUSDT', 'FORMUSDT',
]
